name: TypeScript CI
on:
  push:
    branch: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Test
      run: |
        cd typescript
        npm install
        sh test.sh